import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

        <h1>Google search Engine clone by Hamza using tailwind css</h1>

    </div>
  )
}
